export const INCREASE_COUNTER_VALUE="INCREASE_COUNTER_VALUE";
export const DECREASE_COUNTER_VALUE="DECREASE_COUNTER_VALUE";
export const DECREASE_COUNTER="DECREASE_COUNTER";
export const INCREASE_COUNTER="INCREASE_COUNTER";